apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: atlasfs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: gcr.io/atlas-fs-472018/gateway:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: REDIS_ADDR
          value: "redis:6379"
        - name: PORT
          value: "8080"
        - name: VERSION
          value: "1.0.0"
        - name: POSTGRES_HOST
          value: "104.197.234.56"
        - name: POSTGRES_PASSWORD
          value: "LawdaYaadNahiRahega"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: atlasfs
spec:
  type: LoadBalancer
  selector:
    app: gateway
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
