name: Build and Deploy to GKE

on:
  push:
    branches:
      - main
    paths:
      - 'services/**'
      - 'k8s/**'
      - '.github/workflows/**'

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GKE_CLUSTER: atlas-fs-472018  # Hard-coded to be safe
  GKE_ZONE: us-central1
  REGISTRY: gcr.io

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      services: ${{ steps.detect.outputs.services }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      
      - id: detect
        run: |
          CHANGED_FILES=$(git diff --name-only HEAD^ HEAD || echo "services/")
          SERVICES=""
          
          for service in gateway upload storage metadata download; do
            if echo "$CHANGED_FILES" | grep -q "services/$service/"; then
              SERVICES="$SERVICES $service"
            fi
          done
          
          if [ -z "$SERVICES" ]; then
            SERVICES="gateway"  # Default to gateway if nothing detected
          fi
          
          echo "Changed services: $SERVICES"
          echo "services=$SERVICES" >> $GITHUB_OUTPUT

  build-and-deploy:
    needs: detect-changes
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # FIXED: Better Google Cloud authentication
    - name: Setup Cloud SDK
      uses: google-github-actions/setup-gcloud@v0
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: atlas-fs-472018
        export_default_credentials: true

    # NEW: Authenticate with service account
    - name: Authenticate to Google Cloud
      run: |
        echo "${{ secrets.GCP_SA_KEY }}" | base64 -d > /tmp/gcp-key.json
        gcloud auth activate-service-account --key-file=/tmp/gcp-key.json
        gcloud config set project atlas-fs-472018
        gcloud config set compute/zone us-central1
        gcloud config set compute/region us-central1

    - name: Configure Docker for GCR
      run: |
        gcloud auth configure-docker --quiet

    - name: Get GKE credentials
      run: |
        gcloud container clusters get-credentials atlas-fs-472018 --region us-central1

    - name: Build and Deploy Services
      run: |
        SERVICES="${{ needs.detect-changes.outputs.services }}"
        
        for SERVICE in $SERVICES; do
          if [ "$SERVICE" != "none" ] && [ -d "services/$SERVICE" ]; then
            echo "Building $SERVICE..."
            
            # Build Docker image
            docker build -t gcr.io/atlas-fs-472018/$SERVICE:$GITHUB_SHA \
                         -t gcr.io/atlas-fs-472018/$SERVICE:latest \
                         -f services/$SERVICE/Dockerfile .
            
            # Push to GCR
            docker push gcr.io/atlas-fs-472018/$SERVICE:$GITHUB_SHA
            docker push gcr.io/atlas-fs-472018/$SERVICE:latest
            
            # Update Kubernetes deployment
            kubectl set image deployment/$SERVICE \
                    $SERVICE=gcr.io/atlas-fs-472018/$SERVICE:$GITHUB_SHA \
                    -n atlasfs || echo "Deployment $SERVICE not found, creating it..."
            
            # If deployment doesn't exist, create it
            if ! kubectl get deployment $SERVICE -n atlasfs; then
              kubectl apply -f k8s/$SERVICE.yaml
            fi
          fi
        done

    - name: Verify Deployment
      run: |
        kubectl get pods -n atlasfs
        kubectl get services -n atlasfs