# .github/workflows/deploy.yml
name: Build and Deploy to GKE

on:
  push:
    branches:
      - main
    paths:
      - 'services/**'
      - 'k8s/**'
      - '.github/workflows/**'

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GKE_CLUSTER: ${{ secrets.GKE_CLUSTER }}
  GKE_ZONE: ${{ secrets.GKE_ZONE }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # THIS IS THE FIX - Proper authentication
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Setup Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    - name: Configure Docker for Artifact Registry
      run: |
        gcloud auth configure-docker us-central1-docker.pkg.dev

    - name: Install kubectl
      run: |
        gcloud components install kubectl

    - name: Get GKE credentials
      run: |
        gcloud container clusters get-credentials ${{ env.GKE_CLUSTER }} --region ${{ env.GKE_ZONE }}

    - name: Build and Push Gateway
      run: |
        docker build -t us-central1-docker.pkg.dev/${{ env.PROJECT_ID }}/atlasfs-repo/gateway:${{ github.sha }} \
                     -t us-central1-docker.pkg.dev/${{ env.PROJECT_ID }}/atlasfs-repo/gateway:latest \
                     -f services/gateway/Dockerfile .
        
        docker push us-central1-docker.pkg.dev/${{ env.PROJECT_ID }}/atlasfs-repo/gateway:${{ github.sha }}
        docker push us-central1-docker.pkg.dev/${{ env.PROJECT_ID }}/atlasfs-repo/gateway:latest

    - name: Deploy Gateway
      run: |
        kubectl set image deployment/gateway \
          gateway=us-central1-docker.pkg.dev/${{ env.PROJECT_ID }}/atlasfs-repo/gateway:${{ github.sha }} \
          -n atlasfs
        
        kubectl rollout status deployment/gateway -n atlasfs

    - name: Verify Deployment
      run: |
        kubectl get pods -n atlasfs
        kubectl get services -n atlasfs