name: Build and Deploy to GKE

on:
  push:
    branches:
      - main
    paths:
      - 'services/**'
      - 'k8s/**'
      - '.github/workflows/**'

env:
  PROJECT_ID: atlas-fs-472018
  GKE_CLUSTER: atlas-fs-472018
  GKE_ZONE: us-central1
  REGISTRY: gcr.io

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # CORRECT WAY to Authenticate
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'

    - name: Configure Docker for Artifact Registry  # CHANGED THIS
      run: |
        gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

    - name: Get GKE credentials
      run: |
        gcloud container clusters get-credentials atlas-fs-472018 --region us-central1

    - name: Build and Push Gateway
      run: |
        # Build the Docker image
        docker build -t us-central1-docker.pkg.dev/atlas-fs-472018/atlasfs-repo/gateway:${{ github.sha }} \
                     -t us-central1-docker.pkg.dev/atlas-fs-472018/atlasfs-repo/gateway:latest \
                     -f services/gateway/Dockerfile .
        
        # Push to GCR
        docker push us-central1-docker.pkg.dev/atlas-fs-472018/atlasfs-repo/gateway:${{ github.sha }}
        docker push us-central1-docker.pkg.dev/atlas-fs-472018/atlasfs-repo/gateway:latest

    - name: Deploy to GKE
      run: |
        # Apply the deployment
        kubectl apply -f k8s/gateway.yaml
        
        # Update the image
        kubectl set image deployment/gateway \
                gateway=us-central1-docker.pkg.dev/atlas-fs-472018/atlasfs-repo/gateway:${{ github.sha }} \
                -n atlasfs
        
        # Check rollout status
        kubectl rollout status deployment/gateway -n atlasfs

    - name: Verify Deployment
      run: |
        kubectl get pods -n atlasfs
        kubectl get services -n atlasfs