# .github/workflows/deploy.yml
name: Build and Deploy to GKE

on:
  push:
    branches:
      - main
    paths:
      - 'services/**'
      - 'k8s/**'
      - '.github/workflows/**'

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GKE_CLUSTER: ${{ secrets.GKE_CLUSTER }}
  GKE_ZONE: ${{ secrets.GKE_ZONE }}
  REGISTRY: gcr.io

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Google Cloud
      uses: google-github-actions/setup-gcloud@v1
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        export_default_credentials: true

    - name: Configure Docker for GCR
      run: |
        gcloud auth configure-docker

    - name: Get GKE credentials
      run: |
        gcloud container clusters get-credentials $GKE_CLUSTER --region $GKE_ZONE

    - name: Build and Deploy Gateway
      if: contains(github.event.head_commit.modified, 'services/gateway')
      run: |
        docker build -t $REGISTRY/$PROJECT_ID/gateway:$GITHUB_SHA \
                     -t $REGISTRY/$PROJECT_ID/gateway:latest \
                     -f services/gateway/Dockerfile .
        
        docker push $REGISTRY/$PROJECT_ID/gateway:$GITHUB_SHA
        docker push $REGISTRY/$PROJECT_ID/gateway:latest
        
        kubectl set image deployment/gateway \
                gateway=$REGISTRY/$PROJECT_ID/gateway:$GITHUB_SHA \
                -n atlasfs || echo "Gateway deployment not found"

    - name: Build and Deploy Upload
      if: contains(github.event.head_commit.modified, 'services/upload')
      run: |
        docker build -t $REGISTRY/$PROJECT_ID/upload:$GITHUB_SHA \
                     -t $REGISTRY/$PROJECT_ID/upload:latest \
                     -f services/upload/Dockerfile .
        
        docker push $REGISTRY/$PROJECT_ID/upload:$GITHUB_SHA
        docker push $REGISTRY/$PROJECT_ID/upload:latest
        
        kubectl set image deployment/upload \
                upload=$REGISTRY/$PROJECT_ID/upload:$GITHUB_SHA \
                -n atlasfs || echo "Upload deployment not found"

    - name: Verify Deployment
      run: |
        kubectl get pods -n atlasfs
        kubectl get services -n atlasfs
    
    - name: Deploy Gateway
      run: |
        # Update deployment with new image
        kubectl set image deployment/gateway \
          gateway=$REGISTRY/$PROJECT_ID/gateway:$GITHUB_SHA \
          -n atlasfs
        
        # Wait for rollout
        kubectl rollout status deployment/gateway -n atlasfs