# .github/workflows/deploy.yml
name: Deploy to GKE

on:
  push:
    branches: [main]

env:
  PROJECT_ID: atlas-fs-472018
  GKE_CLUSTER: atlas-fs-472018
  GKE_ZONE: us-central1
  REGION: us-central1

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - id: auth
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - uses: google-github-actions/setup-gcloud@v1
      with:
        install_components: 'gke-gcloud-auth-plugin'

    - name: Configure Docker and Kubectl
      run: |
        # Configure Docker
        gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev
        
        # Install kubectl if needed
        gcloud components install kubectl
        
        # Get cluster credentials
        gcloud container clusters get-credentials ${{ env.GKE_CLUSTER }} --region ${{ env.GKE_ZONE }}

    - name: Build and Deploy Gateway
      run: |
        # Build gateway
        docker build -t ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/atlasfs-repo/gateway:${{ github.sha }} \
                     -t ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/atlasfs-repo/gateway:latest \
                     -f services/gateway/Dockerfile .
        
        # Push gateway
        docker push ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/atlasfs-repo/gateway:${{ github.sha }}
        docker push ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/atlasfs-repo/gateway:latest
        
        # Deploy gateway
        kubectl apply -f k8s/gateway.yaml
        kubectl set image deployment/gateway gateway=${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/atlasfs-repo/gateway:${{ github.sha }} -n atlasfs

    - name: Build and Deploy Upload
      run: |
        # Build upload
        docker build -t ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/atlasfs-repo/upload:${{ github.sha }} \
                     -t ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/atlasfs-repo/upload:latest \
                     -f services/upload/Dockerfile .
        
        # Push upload
        docker push ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/atlasfs-repo/upload:${{ github.sha }}
        docker push ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/atlasfs-repo/upload:latest
        
        # Deploy upload
        kubectl apply -f k8s/upload.yaml
        kubectl set image deployment/upload upload=${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/atlasfs-repo/upload:${{ github.sha }} -n atlasfs

    - name: Wait for Rollout
      run: |
        kubectl rollout status deployment/gateway -n atlasfs --timeout=120s || true
        kubectl rollout status deployment/upload -n atlasfs --timeout=120s || true

    - name: Verify Deployment
      run: |
        echo "=== Deployed Pods ==="
        kubectl get pods -n atlasfs
        echo ""
        echo "=== Services ==="
        kubectl get services -n atlasfs